
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std140, binding = 1) uniform PerFrameData
{
	vec4 cameraPos;
	vec4 frustumPlanes[4]; // Ignoring near and far plane
    uvec4 lodDrawInfos[2]; // 4 pairs of <firstIndex, count> representing the 4 LOD levels, packed into uvec4 cause std140 is lame
    vec3 lodDistancesSQ;
	uint numShapesToCull;
};

struct BoundingSphere
{
	float center[3];
    float radius;
};

layout(std430, binding = 2) buffer BoundingSpheres
{
	BoundingSphere inBoundingSpheres[];
};

struct DrawCommand
{
	uint count;
	uint instanceCount;
	uint firstIndex;
	uint baseVertex;
	uint baseInstance;
};

layout(std430, binding = 3) buffer DrawCommands
{
	DrawCommand inDrawCommands[];
};

//layout(std430, binding = 4) buffer NumVisibleMeshes
//{
//	uint numVisibleMeshes;
//};

float planeDistance(vec4 plane, vec3 point) {
    return plane.w + dot(plane.xyz, point);
}

uint sphereCheckAndUpdateLOD()
{
    const uint idx = gl_GlobalInvocationID.x;
	BoundingSphere sphere = inBoundingSpheres[inDrawCommands[idx].baseInstance];
    
    // Sphere Check
    // IGNORING FAR AND NEAR CLIPPING PLANE
    vec3 offset = vec3(sphere.center[0], sphere.center[1], sphere.center[2]) - cameraPos.xyz;
    // Frustum assumes camera always at 0 so we simply use an offset
	for (int p = 0; p < 4; ++p) { 
        if (planeDistance(frustumPlanes[p], offset) <= -sphere.radius) {
            return 0;
        }
    }
    
    // Update LOD
    float distance2 = dot(offset, offset);
    if (distance2 < lodDistancesSQ[0]) {
        inDrawCommands[idx].firstIndex = lodDrawInfos[0].x;
        inDrawCommands[idx].count = lodDrawInfos[0].y;
    } else if (distance2 < lodDistancesSQ[1]) {
        inDrawCommands[idx].firstIndex = lodDrawInfos[0].z;
        inDrawCommands[idx].count = lodDrawInfos[0].w;
    } else if (distance2 < lodDistancesSQ[2]) {
        inDrawCommands[idx].firstIndex = lodDrawInfos[1].x;
        inDrawCommands[idx].count = lodDrawInfos[1].y;
    } else {
        inDrawCommands[idx].firstIndex = lodDrawInfos[1].z;
        inDrawCommands[idx].count = lodDrawInfos[1].w;
    }

    return 1;
}

void main()
{
	const uint idx = gl_GlobalInvocationID.x;

	if (idx < numShapesToCull)
	{
		uint numInstances = sphereCheckAndUpdateLOD();
		inDrawCommands[idx].instanceCount = numInstances;
		//atomicAdd(numVisibleMeshes, numInstances);
	}
}
