const char* FIRST_NAMES_MALE[] = {
    "Achatz",
    "Reyneke",
    "Tönnies",
    "Börries",
    "Johannes",
    "Statius",
    "Henning",
    "Hinrik",
    "Hans",
    "Franz",
    "Andreas",
    "Cord",
    "Marten",
    "Conrad",
    "Hieronymus",
    "Henni",
    "Heinrich",
    "Arendt",
    "Jasper",
    "Jost",
    "Bartold",
    "Baltzer",
    "Harmen",
    "Claus",
    "Bernhard",
    "Bruno",
    "Hermann",
    "Peter",
    "Sergius",
    "Sander",
    "Ahasver",
    "Brand",
    "Wolff",
    "Carsten",
    "Leonhard",
    "Wilhelm",
    "Dirick",
    "Burchard",
    "Liborius",
    "Melchior",
    "Balthasar",
    "Dietrich",
    "Ludwig",
    "Wulbrand",
    "Hilmar",
    "Lorenz",
    "Asmus",
    "Vinzenz",
    "Valentin",
    "Michael",
    "Siegfried",
    "Lambert",
    "Philipp",
    "Albert",
    "Alexander",
    "Joachim",
    "Erasmus",
    "Michel",
    "Nikolaus",
    "Thorir",
    "Erdmann",
    "Markward",
    "Jürgen",
    "Markus",
    "Hippolytus",
    "Simon",
    "Ewald",
    "Clages",
    "Ulrich",
    "Kurt",
    "Konrad",
    "Barnim",
    "Wartislaw",
    "Bogislaw",
    "Reynmar",
    "Paul",
    "Rickert",
    "Thomas",
    "Georg",
    "Karl",
    "Werner",
    "Everhard",
    "Emmanuel",
    "Viktor",
    "Felix",
    "Daniel",
    "Kaspar",
    "Zacharias",
    "Jackso",
    "Volcmer",
    "Arnold",
    "Moritz",
    "Volkwart",
    "Erich",
    "Albus",
    "Dinnies",
    "Sabellus",
    "Otto",
    "Tews",
};

const char* FIRST_NAMES_FEMALE[] = {
    "Katharina",
    "Margarete",
    "Elisa",
    "Barbara",
    "Berta",
    "Magdalena",
    "Anna",
    "Justine",
    "Taleke",
    "Juliane",
    "Erdmuth",
    "Emerentia",
    "Engel",
    "Gertrud",
    "Ilsebe",
    "Klara",
    "Liboria",
    "Dorothea",
    "Tita",
    "Ilse",
    "Regina",
    "Hedwig",
    "Adelheid",
    "Metteke",
    "Ursula",
    "Agneta",
    "Christina",
    "Maria",
    "Susanne",
    "Lucia",
    "Gesa",
    "Charlotte",
    "Adelheid",
    "Euphemia",
    "Otilia",
    "Felicitas",
    "Lisa",
    "Irmgard",
    "Agnes",
    "Apollonia",
    "Martha",
    "Eusebia",
    "Eva",
    "Isengart",
    "Kunigunde",
    "Guda",
    "Amelia",
    "Antonetta",
    "Cordula",
    "Susanna",
    "Eleonora",
    "Liboria",
    "Kyneke",
    "Tebbe",
    "Hedeke",
    "Cecislawa",
    "Olegardis",
    "Walburgis",
    "Wobeke",
    "Mynteke",
    "Sybilla",
    "Agnesa",
    "Tilseke",
    "Trude",
    "Wendele",
    "Judith",
    "Euphrosina",
    "Hippolyta",
    "Alveke",
    "Modesta",
    "Benigna",
    "Alverdis",
    "Cecilia",
    "Merge",
    "Mette",
    "Mechthild",
    "Ottilie",
    "Beate",
    "Wille",
    "Armgard",
    "Palladia",
    "Engelke",
    "Sidonia",
    "Olicke",
    "Runne",
    "Melusina",
    "Elsa",
    "Catrina",
    "Dortia",
    "Rixa",
    "Sabina",
    "Julia",
    "Cunne",
    "Heilweig",
    "Esther",
    "Gisela",
    "Helena",
    "Lefeken",
    "Grete",
};

const char* LAST_NAMES[] = {
    "Ärtzgräber",
    "Baol",
    "Beck",
    "Bender",
    "Blanckenbeyl",
    "Blum",
    "Breutel",
    "Chunius",
    "Crommel",
    "Culman",
    "Drapp",
    "Drau",
    "Faber",
    "Fischer",
    "Fürck",
    "Gertenheyer",
    "Gros",
    "Heuß",
    "Maß",
    "Hitzfeld",
    "Holsteges",
    "Hufeisen",
    "Hyenerer",
    "Keiser",
    "Kiefer",
    "Klapperbach",
    "Knorr",
    "Koch",
    "Kraus",
    "Zöllner",
    "Wyndt",
    "Brand",
    "Wimpeling",
    "Weller",
    "Spitz",
    "Vogt",
    "Sonnenschmidt",
    "Sohler",
    "Saxler",
    "Scherin",
    "Rüthgen",
    "Rühl",
    "Röder",
    "Pors",
    "Pomereydt",
    "Polich",
    "Placzfus",
    "Pellifex",
    "Nordeck",
    "Lotley",
    "Leyendecker",
    "Nonnenmacher",
    "Klockenhencker",
    "Kalbach",
    "Bavemann",
    "Beddecker",
    "Blanckscheehn",
    "Caroc",
    "Colbert",
    "Corswant",
    "Crugher",
    "Dachtenbicht",
    "Dargatz",
    "Engelbrecht",
    "Erskein",
    "Friso",
    "Frobose",
    "Glewing",
    "Glineke",
    "Gottschalk",
    "Graskröger",
    "Hagemeister",
    "Hannemann",
    "Middelstedt",
    "Neuschwager",
    "Oldehaver",
    "Penningsdorf",
    "Pritlevitz",
    "Quant",
    "Range",
    "Saccus",
    "Saltwedel",
    "Schwartzerdt",
    "Schupplenberg",
    "Tabbert",
    "Tarncke",
    "Tideböhl",
    "Uteske",
    "Vargatz",
    "Vlesch",
    "Warendorp",
    "Wikbold",
    "Zander",
    "Zimdars",
    "Düvel",
    "Großcurt",
    "Oppermann",
    "Wucherpfennig",
    "Weckenesel",
};

const char* LAKE_NAMES[] = {
    "Gold Lake",
    "Lake of Death",
    "Green Lake",
    "Crystal Mirror Lake",
    "Silent Waters",
    "Azure Depths",
    "Whispering Lake",
    "Misty Vale Lake",
    "Emerald Basin",
    "Twilight Lake",
    "Echoing Lake",
    "Frozen Tears Lake",
    "Sapphire Lagoon",
    "Moonlit Lake",
    "Starfall Lake",
    "Dragon's Breath Lake",
    "Serenity Lake",
    "Raven's Beak Lake",
    "Crimson Lake",
    "Sunset Lake",
    "Duskwater Lake",
    "Obsidian Lake",
    "Skyreach Lake",
    "Mystic Lake",
    "Phantom Lake",
    "Shimmering Lake",
    "Stormwatch Lake",
    "Lake of the Ancients",
    "Radiant Lake",
    "Wraithwater Lake",
    "Thunder Lake",
    "Ivory Lake",
    "Shadowmere",
    "Cerulean Lake",
    "Frostfire Lake",
    "Glimmering Lake",
    "Lake of Whispers",
    "Blackglass Lake",
    "Veilfall Lake",
    "Soulwater Lake",
    "Blighted Lake",
    "Dewdrop Lake",
    "Sunrise Lake",
    "Winding River Lake",
    "Forbidden Lake",
    "Galeforce Lake",
    "Lake of Illusions",
    "Mirror Lake",
    "Aurora Lake",
    "Eclipse Lake",
    "Crestfall Lake",
    "Lunar Lake",
    "Sanguine Lake",
    "Ashen Lake",
    "Lake of Echoes",
    "Winter's Mirror Lake",
    "Celestial Lake",
    "Wilderlake",
    "Tranquil Lake",
    "Lake of the Sage",
    "Enchanted Lake",
    "Lake of Legends",
    "Inferno Lake",
    "Willowmere",
    "Rune Lake",
    "Onyx Lake",
    "Pinecrest Lake",
    "Nightshade Lake",
    "Chillwind Lake",
    "Grove Lake",
    "Lake of the Seer",
    "Vortex Lake",
    "Lake of Dreams",
    "Opal Lake",
    "Thornlake",
    "Lake of Serpents",
    "Foggy Lake",
    "Arcane Lake",
    "Lake Solitude",
    "Diamond Lake",
    "Lake of the Oracle",
    "Stardust Lake",
    "Tempest Lake",
    "Lake Nirvana",
    "Lake of Miracles",
    "Lake of the Forgotten",
    "Rustic Lake",
    "Lake of Eternity",
    "Sandswept Lake",
    "Lake of Mysteries",
    "Everlake",
    "Lake Infinity",
    "Midnight Lake",
    "Lake of Spirits",
    "Lake of the Lost",
    "Timeless Lake",
    "Lake of Reflections",
    "Lake of Fire"
};

const char* OCEAN_NAMES[] = {
    "Black Ocean",
    "Infinite Blue",
    "Celestial Sea",
    "Mystic Ocean",
    "Abyssal Depths",
    "Crimson Tide",
    "Emerald Expanse",
    "Whispering Waves",
    "Endless Waters",
    "Shrouded Sea",
    "Moonlit Ocean",
    "Sapphire Depths",
    "Eternal Sea",
    "Stormwrath Ocean",
    "Azure Main",
    "Phantom Sea",
    "Starlight Ocean",
    "Silver Sea",
    "Twilight Depths",
    "Serenity Ocean",
    "Sunken Depths",
    "Maelstrom Sea",
    "Luminous Ocean",
    "Frozen Sea",
    "Lost Horizon",
    "Mirage Ocean",
    "Boreal Sea",
    "Radiant Ocean",
    "Shadow Sea",
    "Opal Waters",
    "Mystical Ocean",
    "Calm Expanse",
    "Forgotten Sea",
    "Ghostly Ocean",
    "Dreamer's Sea",
    "Mythic Ocean",
    "Tempest Sea",
    "Sunfire Ocean",
    "Hidden Depths",
    "Ancient Sea",
    "Ivory Ocean",
    "Wandering Waves",
    "Duskwater Sea",
    "Ocean of Fate",
    "Chaos Ocean",
    "Halcyon Sea",
    "Veiled Depths",
    "Enchanted Ocean",
    "Nebula Sea",
    "Dawn's Ocean",
    "Tidal Memory",
    "Echoing Sea",
    "Harmony Ocean",
    "Eclipse Waters",
    "Crystal Sea",
    "Wild Ocean",
    "Siren's Depths",
    "Obsidian Sea",
    "Vast Expanse",
    "Stormcaller Ocean",
    "Reverie Sea",
    "Fathomless Depths",
    "Wraithwater Ocean",
    "Mirrored Sea",
    "Glimmering Ocean",
    "Thalassic Depths",
    "Vortex Sea",
    "Arcadian Ocean",
    "Nightmare Sea",
    "Zephyr Ocean",
    "Timeless Waters",
    "Prismatic Sea",
    "Oblivion Ocean",
    "Coral Depths",
    "Windward Sea",
    "Orion's Ocean",
    "Soul Sea",
    "Flameheart Ocean",
    "Everchanging Depths",
    "Eldritch Sea",
    "Leviathan's Lair",
    "Aurora Ocean",
    "Nether Sea",
    "Turbulent Depths",
    "Tideless Ocean",
    "Solar Sea",
    "Waves of Wonder",
    "Ocean of Whispers",
    "Terra Ocean",
    "Galactic Sea",
    "Isleward Ocean",
    "Omen's Sea",
    "Sea of Tranquility",
    "Rift Ocean",
    "Dragon's Sea",
    "Sunken Dreams",
    "Lorelei Depths",
    "Seafarer's Ocean",
    "Starborn Sea",
    "Ocean of Twilight",
    "Ethereal Sea",
    "Gale's Ocean",
    "Heavenly Waters",
    "Chimerical Sea",
    "Ocean of Time"
};

const char* LARGE_ISLAND_NAMES[] = {
    "Xatuan",
    "Ipox",
    "Vuplea",
    "Veicora",
    "Odroth",
    "Riashuhuin",
    "Zephyria",
    "Thundarion",
    "Eldoria",
    "Solara",
    "Mystara",
    "Avaloria",
    "Gaiathorn",
    "Draconis",
    "Terranova",
    "Luminar",
    "Aetherius",
    "Celestia",
    "Obsidion",
    "Nimoria",
    "Rivenwood",
    "Auroria",
    "Maridia",
    "Galvoria",
    "Ironhold",
    "Frostvale",
    "Sunspire",
    "Shadowfell",
    "Stormguard",
    "Terraflux",
    "Arcanix",
    "Borealys",
    "Crystalis",
    "Dragontail",
    "Eclipsea",
    "Faywild",
    "Gloomreach",
    "Halcyonia",
    "Ivory Shores",
    "Jade Empire",
    "Kingsland",
    "Lorehaven",
    "Mythica",
    "Netherworld",
    "Oceanus",
    "Pandemonium",
    "Quintara",
    "Runeheim",
    "Starhaven",
    "Tempestia",
    "Umbra",
    "Vortexia",
    "Whisperwind",
    "Xanadu",
    "Yggdrasil",
    "Zenithar",
    "Abyssia",
    "Blightwood",
    "Crescentia",
    "Duskwyn",
    "Ethereal Plains",
    "Flameward",
    "Glacierfall",
    "Heavensgate",
    "Infernia",
    "Juxtapose",
    "Krynn",
    "Lothloria",
    "Mysthaven",
    "Nightbloom",
    "Oblivion Peak",
    "Prismatica",
    "Quartzon",
    "Rapture",
    "Skyward Isles",
    "Terra Firma",
    "Uncharted Realms",
    "Vanguard",
    "Witchwood",
    "Xystus",
    "Yieldmore",
    "Zephyros",
    "Aurumia",
    "Bravestone",
    "Chronos Isle",
    "Dawnridge",
    "Eterna",
    "Frostgard",
    "Grimscape",
    "Horizon's End",
    "Imperia",
    "Jade Frontier",
    "Kilnara",
    "Lumina",
    "Mirage Vale",
    "Necropolis",
    "Oathsworn",
    "Pinnacle",
    "Quarion",
    "Riftshade",
    "Sylvanor",
    "Titan's Reach",
    "Utopia",
    "Verdant Plains",
    "Windborne",
    "Xenon",
    "Ymir's Throne",
    "Zion"
};

const char* SMALL_ISLAND_NAMES[] = {
    "Eirie",
    "Jewel Island",
    "Lusca Shores",
    "Shizumi Bay",
    "Kai Rock",
    "Moonstone Isle",
    "Sapphire Cay",
    "Emerald Atoll",
    "Coral Haven",
    "Pearl Beach",
    "Nimbus Isle",
    "Azure Retreat",
    "Driftwood Key",
    "Mystic Sands",
    "Starfish Isle",
    "Turtle Cove",
    "Whispering Reef",
    "Silver Shore",
    "Mermaid's Rest",
    "Gull's Nest",
    "Sunset Key",
    "Pirate's Hideout",
    "Dolphin Lagoon",
    "Seagull Point",
    "Stormwatch Islet",
    "Wavecrest Haven",
    "Riptide Rock",
    "Mariner's Moor",
    "Siren's Call",
    "Lonely Isle",
    "Hidden Cove",
    "Oyster Bay",
    "Mangrove Island",
    "Breeze Isle",
    "Tidepool Beach",
    "Fisher's Folly",
    "Seashell Shoal",
    "Dune's Edge",
    "Palm Paradise",
    "Shipwreck Island",
    "Bounty Beach",
    "Kraken's Lair",
    "Treasure Trove",
    "Squall's End",
    "Castaway Key",
    "Fogbank Isle",
    "Saltwind Sandbar",
    "Spindrift Strand",
    "Misty Archipelago",
    "Sailor's Haven",
    "Windward Isle",
    "Skull Rock",
    "Neptune's Nook",
    "Flotsam Island",
    "Sunrise Atoll",
    "Anchor's Rest",
    "Seafarer's Stop",
    "Crimson Cay",
    "Lighthouse Isle",
    "Falcon's Roost",
    "Opal Outcrop",
    "Blue Lagoon",
    "Harbor Island",
    "Waverider Islet",
    "Moonshadow Bay",
    "Tropicana Key",
    "Schooner Shoal",
    "Thalassa's Throne",
    "Navigator's Niche",
    "Sable Shore",
    "Thunderclap Reef",
    "Halcyon Isle",
    "Squid's Haven",
    "Paradise Peak",
    "Voyager's Venture",
    "Pelican Point",
    "Haven's Hold",
    "Coral Crest",
    "Narwhal's Neck",
    "Sands of Serenity",
    "Marlin's Mound",
    "Periwinkle Point",
    "Reef's End",
    "Azure Ascent",
    "Bamboo Bay",
    "Echoing Eddy",
    "Seaweed Strand",
    "Manta Ray's Rise",
    "Puffin's Perch",
    "Cliffside Cay",
    "Dragonfly Dock",
    "Seabird Sound",
    "Orca's Outlook",
    "Hibiscus Hideaway",
    "Wave Whisperer's Way",
    "Tropic's Touch",
    "Starlit Sanctuary",
    "Seafoam Shores",
    "Jellyfish Junction"
};

const char* SETTLEMENT_NAMES[] = {
    "Ravenwood",
    "Elderglen",
    "Whisperwind Village",
    "Dawnridge",
    "Silverpine Hamlet",
    "Frostfall Town",
    "Sunset Hollow",
    "Mystic Springs",
    "Ironforge City",
    "Briarcliff",
    "Thornvale",
    "Shadowmoor",
    "Dragon's Rest",
    "Glimmerbrook",
    "Havenfield",
    "Stormwatch",
    "Starlight Town",
    "Harborview",
    "Emerald Haven",
    "Bouldercrest",
    "Wolfsbane Village",
    "Crystal Lake Town",
    "Moonshadow Hamlet",
    "Solstice City",
    "Oakwood Grove",
    "Tidebreak",
    "Windward Village",
    "Marblegate",
    "Twilight Falls",
    "Serenity Springs",
    "Pinegrove",
    "Redwater",
    "Skyreach City",
    "Lighthaven",
    "Aurora Heights",
    "Cinderwood",
    "Azure Bay",
    "Goldenleaf Hamlet",
    "Nightbreeze",
    "Willowdale",
    "Duskwood Village",
    "Ivystone",
    "Falcon's Nest",
    "Sapphire Shore",
    "Meadowmere",
    "Northwind",
    "Rivercross",
    "Hollowrock",
    "Fogshore",
    "Rainshadow",
    "Eagle's Perch",
    "Crestfall Village",
    "Stonehill",
    "Galeport",
    "Mirage City",
    "Flameheart",
    "Evergreen Town",
    "Ironhold",
    "Seabreeze Village",
    "Winterspire",
    "Jade Valley",
    "Kingshaven",
    "Storm's End",
    "Driftwood",
    "Fairview",
    "Highgarden",
    "Lakeshore",
    "Maplewood",
    "New Dawn",
    "Orchard's End",
    "Pebblebrook",
    "Quarryville",
    "Rivertown",
    "Sunblaze Hamlet",
    "Timberline",
    "Umbra Village",
    "Valewatch",
    "Wildthorn",
    "Xylopolis",
    "Yewwood",
    "Zephyrfield",
    "Ashgrove",
    "Bluestone",
    "Crestwood",
    "Dunewatch",
    "Elmstone",
    "Fernhill",
    "Glimmerveil",
    "Hearthglen",
    "Ironmire",
    "Jasperhold",
    "Kestrel's Roost",
    "Lunar Bay",
    "Mirthwood",
    "Netherfield",
    "Oakheart",
    "Pinefall",
    "Quartzhill",
    "Ridgecrest",
    "Silverstream",
    "Terravale",
    "Upland Grove",
    "Violet Vale",
    "Wraithwood",
    "Zenith Peak"
};
