#pragma once


// ================= SSBO Binding points =================
constexpr GLuint BUFFER_BASE_GLOBAL_UBO = 0; // Always bound
constexpr GLuint BUFFER_BASE_GLOBAL_MATERIAL_SSBO = 1; // Always bound
constexpr GLuint BUFFER_BASE_MESH_UBO = 2;
constexpr GLuint BUFFER_BASE_MESH_SSBO = 3;

constexpr GLuint BUFFER_BASE_MODEL_IMPOSTOR_DATA_SSBO = 3;
constexpr GLuint BUFFER_BASE_MODEL_IMPOSTOR_MATERIALS_SSBO = 4;

constexpr GLuint BUFFER_BASE_MODEL_VARIANT_DATA_SSBO = 4;
constexpr GLuint BUFFER_BASE_TERRAIN_COLOR_MAPS_SSBO = 4;
constexpr GLuint BUFFER_BASE_DEBUG_MESH_GENERIC_SSBO = 4;
constexpr GLuint BUFFER_BASE_SUBMESH_WIND_TYPES_BINDING_POINT = 5;
constexpr GLuint BUFFER_BASE_SKINNING_MATRICES = 6;
constexpr GLuint BUFFER_BASE_MODEL_DAMAGE_DATA_SSBO = 7;
constexpr GLuint BUFFER_BASE_MODEL_TRANSFORMS_SSBO = 8;
constexpr GLuint BUFFER_BASE_CROSSFADE_SSBO = 9;
constexpr GLuint BUFFER_BASE_MUTATION_SSBO = 9;

constexpr GLuint BUFFER_BASE_TERRAIN_SURFACE_DATA_SSBO = 5;
constexpr GLuint BUFFER_BASE_TERRAIN_SURFACE_OVERLAY_DATA_SSBO = 6;

constexpr GLuint BUFFER_BASE_PARTICLE_POSITIONS_SSBO = 4;
constexpr GLuint BUFFER_BASE_PARTICLE_SCALES_SSBO = 5;
constexpr GLuint BUFFER_BASE_PARTICLE_COLORS_SSBO = 6;
constexpr GLuint BUFFER_BASE_PARTICLE_HDR_COLORS_SSBO = 7;
constexpr GLuint BUFFER_BASE_PARTICLE_MATERIALS_SSBO = 8;
constexpr GLuint BUFFER_BASE_PARTICLE_ROTATIONS_SSBO = 9;

constexpr GLuint BUFFER_BASE_PARTICLE_CUSTOM_DATA_BEGIN = 10;
constexpr GLuint BUFFER_BASE_PARTICLE_CUSTOM_DATA_END = 15;
constexpr GLuint BUFFER_BASE_PARTICLE_CUSTOM_DATA_COUNT = BUFFER_BASE_PARTICLE_CUSTOM_DATA_END - BUFFER_BASE_PARTICLE_CUSTOM_DATA_BEGIN + 1;

constexpr GLuint BUFFER_BASE_GRASS_UBO = 9;
constexpr GLuint BUFFER_BASE_CAMERA_UBO = 10;

// ================= VAO Binding points =================
constexpr GLuint MODEL_TRANSFORMS_BINDING_POINT = 2;
constexpr GLuint MODEL_INSTANCE_DATA_BINDING_POINT = 3;
