
#include "util/noise/snoise3.glsl"
#include "util/noise/cellular3d.glsl"
#include "const/biome_ids.glsl"

const float MOUNTAIN_BLEND = 0.3;
const float SEA_BLEND_TO_BIOME = 0.1;
const float SEA_BLEND_TO_MOUNTAINS = 0.15;
const float PLAINS_PRIORITY = 0.1;


layout(local_size_x = 16, local_size_y = 16) in;

layout(r8, binding = 0) uniform writeonly image2D heightImage;
layout(std430, binding = 0) writeonly restrict buffer HeightData
{
    float heightData[];
};
layout(r8, binding = 1) uniform writeonly image2D biomeImage;
layout(std430, binding = 1) writeonly restrict buffer BiomeData
{
    uint biomeData[];
};

uniform vec2 unWorldCenter;
uniform float unContinentRadius;
uniform float unSeed = 0;
uniform uint unYStride;
uniform ivec2 unVertexOffset;

uniform vec2 unPatchWorldPos;
const float MIN_WORLD_GEN_HEIGHT = -3000.0;
const float MAX_WORLD_GEN_HEIGHT = 3000.0;
const float HEIGHT_VERTEX_SPACING = 2; // Match C++
const float BIOME_VERTEX_SPACING = 8; // Match C++
const uint BIOME_VERTEX_SPACING_DIFF = uint(BIOME_VERTEX_SPACING) / uint(HEIGHT_VERTEX_SPACING);
const float MAX_RADIUS = 15000.0;
const float WORLD_RADIUS = 16536.0;
const float WORLD_RADIUS2 = WORLD_RADIUS * WORLD_RADIUS;
const float OUTER_LERP_DISTANCE = WORLD_RADIUS - MAX_RADIUS;
const float WORLD_EDGE_MIN_DEPTH = -100.0;

float standardNoise(vec3 position, int octaves, float frequency, float persistence, vec2 posOffset, float amplitude, float heightOffset) {
    position.xy += posOffset;
    return (noise(position, octaves, frequency, persistence) + heightOffset) * amplitude;
}
float ridgedNoise(vec3 position, int octaves, float frequency, float persistence, vec2 posOffset, float amplitude, float heightOffset) {
    position.xy += posOffset;
    float noiseVal = noise(position, octaves, frequency, persistence);
    noiseVal = 1.0 - abs(noiseVal);
    return (noiseVal + heightOffset) * amplitude;
}
//void cellularNoise(vec3 position, int octaves, float persistence, float frequency, vec2 posOffset, float amplitude, float heightOffset) {
//    return (noise(position + posOffset, octaves, frequency, persistence) + heightOffset) * amplitude;
//}


float cutNoiseAtStep(float noiseVal, float stepVal) {
    return noiseVal * step(stepVal, noiseVal);
}


int generateBiomes(inout float height, vec3 posInputSeeded) {
    float bestWeight = 0.0;
    int bestBiome = BIOME_Ocean;
    
    if (height <= 0.0) {
        return bestBiome;
    }
    const float seaHeightMultMountains = clamp(height * SEA_BLEND_TO_MOUNTAINS, 0.0, 1.0);
    // TODO: Multiply at end? hmm
    const float seaHeightMult = clamp(height * SEA_BLEND_TO_BIOME, 0.0, 1.0);
    
    // Mountains
    float mountainDist = standardNoise(posInputSeeded.yzx, 5, 0.000166, 0.6, vec2(0, 0), 4.0, -0.15) * seaHeightMultMountains;
    if (mountainDist > 0.0) {
        float mountainWeight = min(mountainDist, 1.0);
        float mountainHeight = cellularNoise3D(posInputSeeded.zxy, 5, 0.00157, 0.65, vec2(0, 0), 300.0, 0.0);
        float mountainDetail = ridgedNoise(posInputSeeded.zxy, 8, 0.001, 0.6, vec2(0, 0), 64.0, 0.0);
        height += (mountainHeight + mountainDetail) * mountainWeight * seaHeightMult;
        bestWeight = mountainWeight;
        bestBiome = BIOME_Mountains;
    }
    
    // Mountains take things over
    if (mountainDist < MOUNTAIN_BLEND) {
        // Plains
        float plainsHeight = standardNoise(posInputSeeded, 6, 0.001, 0.65, vec2(0, 0), 30.0, 0.35);
        float nonMountainWeight = ((MOUNTAIN_BLEND - mountainDist) / MOUNTAIN_BLEND);
        nonMountainWeight = min(nonMountainWeight, 1.0);
        height += plainsHeight * nonMountainWeight * seaHeightMult;
        if (nonMountainWeight > bestWeight) {
            bestBiome = BIOME_Plains;
            bestWeight = 0.0;
        }
    
        // Forest
        float forestDist = standardNoise(posInputSeeded.yxz, 6, 0.001, 0.6, vec2(-1000.0, 0), 5.0, -0.2);
        float forestHeight = standardNoise(posInputSeeded, 3, 0.05, 0.65, vec2(0, 0), 5.0, 0.0);
        float forestWeight = nonMountainWeight * forestDist;
        forestWeight = clamp(forestWeight, 0.0, 1.0);
        height += forestHeight * forestWeight * seaHeightMult;
        if (forestWeight > bestWeight) {
            bestBiome = BIOME_Forest;
            bestWeight = forestWeight;
        }
        
        // Hot springs
        float springsDist = standardNoise(posInputSeeded.zxy, 6, 0.001, 0.6, vec2(1000.0, 0), 3.0, -0.25);
        float springsHeight = standardNoise(posInputSeeded, 2, 0.01, 0.65, vec2(0, 0), 20.0, -0.5);
        float springsWeight = nonMountainWeight * springsDist;
        // Springs lower priority
        springsWeight *= (1.0 - bestWeight);
        springsWeight = clamp(springsWeight, 0.0, 1.0);
        springsHeight = springsHeight * springsWeight * seaHeightMult;
        // Step function
        springsHeight = floor(springsHeight / 2.0) * 2.0;
        height += springsHeight;
        if (springsWeight > bestWeight) {
            bestBiome = BIOME_Hotsprings;
            bestWeight = springsWeight;
        }
    }
    return bestBiome;
}


void main() {   
    const uint idx = gl_GlobalInvocationID.x;
    const uint idy = gl_GlobalInvocationID.y;
    
    const vec3 posInputSeeded = vec3(unPatchWorldPos.x + float(idx) * HEIGHT_VERTEX_SPACING, unPatchWorldPos.y + float(idy) * HEIGHT_VERTEX_SPACING, unSeed);
    
      // Base height
    float height = standardNoise(posInputSeeded, 4, 0.001, 0.7, vec2(0, 0), 10.0, 1.0);
    
    vec2 offsetToCenter = vec2(
        posInputSeeded.x - unWorldCenter.x,
        posInputSeeded.y - unWorldCenter.y
    );
    
    //  TODO: Precompute and interpolate, can cubic interpolate and others
    float manhattanDistanceFromCenter = max(abs(offsetToCenter.x), abs(offsetToCenter.y));

    // Preturb the outline via noise
    const float continentOutlineNoise = standardNoise(vec3(offsetToCenter.x, offsetToCenter.y, unSeed), 8, 0.0002, 0.65, vec2(0.0, 0.0), 3000.0, 0.0);
    float adjustedDistanceFromCenter = manhattanDistanceFromCenter + continentOutlineNoise;

    // Create a fairly circular outline to deep ocean
    height -= max((adjustedDistanceFromCenter - unContinentRadius) * 0.025, 0.0);

    //Split world into subcontinents.
    float continentBreak = standardNoise(posInputSeeded, 8, 0.0001, 0.6, vec2(0, 0), 1.0, 0.1) * 0.5;
    continentBreak = cutNoiseAtStep(continentBreak, 0.0);
    height -= continentBreak * 240.0;
    
    // Enforce water on edge of world
    if (manhattanDistanceFromCenter > MAX_RADIUS) {
        height = mix(height, min(height, WORLD_EDGE_MIN_DEPTH), pow((manhattanDistanceFromCenter - MAX_RADIUS) / OUTER_LERP_DISTANCE, 8.0));
    }
        
    // Biomes  
    const int biome = generateBiomes(height, posInputSeeded);
        
    float finalHeight = clamp(height, MIN_WORLD_GEN_HEIGHT, MAX_WORLD_GEN_HEIGHT);
    
    // Cone world lol
    //finalHeight = 0.0000001 * finalHeight + 500.0 - pow((length(offsetToCenter)), 1.0);

    // Store height
    ivec2 hxy = ivec2(unVertexOffset.x + idx, unVertexOffset.y + idy);
    uint heightIndex = hxy.y * unYStride + hxy.x;
    heightData[heightIndex] = finalHeight;
    imageStore(heightImage, hxy, vec4(clamp((finalHeight + 127.0) - 100.0, 0.0, 255.0) / 255.0, 0.0, 0.0, 0.0));
    
   
    // Store biome
    if (mod(idx, BIOME_VERTEX_SPACING_DIFF) + mod(idy, BIOME_VERTEX_SPACING_DIFF) == 0) {
        ivec2 bxy = ivec2((unVertexOffset.x + idx) / BIOME_VERTEX_SPACING_DIFF, (unVertexOffset.y + idy) / BIOME_VERTEX_SPACING_DIFF);
        uint biomeIndex = bxy.y * (unYStride / BIOME_VERTEX_SPACING_DIFF) + bxy.x;
        biomeData[biomeIndex] = uint(biome);
        imageStore(biomeImage, bxy, vec4(float(biome) / 255.0, 0.0, 0.0, 0.0));
    }
}