#pragma once

bool gliHasAlpha(gli::format format) {
    switch (format) {
        case gli::format::FORMAT_RGBA4_UNORM_PACK16:
        case gli::format::FORMAT_BGRA4_UNORM_PACK16:
        case gli::format::FORMAT_RGB5A1_UNORM_PACK16:
        case gli::format::FORMAT_BGR5A1_UNORM_PACK16:
        case gli::format::FORMAT_A1RGB5_UNORM_PACK16:
        case gli::format::FORMAT_RGBA8_UNORM_PACK8:
        case gli::format::FORMAT_RGBA8_SNORM_PACK8:
        case gli::format::FORMAT_RGBA8_USCALED_PACK8:
        case gli::format::FORMAT_RGBA8_SSCALED_PACK8:
        case gli::format::FORMAT_RGBA8_UINT_PACK8:
        case gli::format::FORMAT_RGBA8_SINT_PACK8:
        case gli::format::FORMAT_RGBA8_SRGB_PACK8:
        case gli::format::FORMAT_BGRA8_UNORM_PACK8:
        case gli::format::FORMAT_BGRA8_SNORM_PACK8:
        case gli::format::FORMAT_BGRA8_USCALED_PACK8:
        case gli::format::FORMAT_BGRA8_SSCALED_PACK8:
        case gli::format::FORMAT_BGRA8_UINT_PACK8:
        case gli::format::FORMAT_BGRA8_SINT_PACK8:
        case gli::format::FORMAT_BGRA8_SRGB_PACK8:
        case gli::format::FORMAT_RGBA8_UNORM_PACK32:
        case gli::format::FORMAT_RGBA8_SNORM_PACK32:
        case gli::format::FORMAT_RGBA8_USCALED_PACK32:
        case gli::format::FORMAT_RGBA8_SSCALED_PACK32:
        case gli::format::FORMAT_RGBA8_UINT_PACK32:
        case gli::format::FORMAT_RGBA8_SINT_PACK32:
        case gli::format::FORMAT_RGBA8_SRGB_PACK32:
        case gli::format::FORMAT_RGB10A2_UNORM_PACK32:
        case gli::format::FORMAT_RGB10A2_SNORM_PACK32:
        case gli::format::FORMAT_RGB10A2_USCALED_PACK32:
        case gli::format::FORMAT_RGB10A2_SSCALED_PACK32:
        case gli::format::FORMAT_RGB10A2_UINT_PACK32:
        case gli::format::FORMAT_RGB10A2_SINT_PACK32:
        case gli::format::FORMAT_BGR10A2_UNORM_PACK32:
        case gli::format::FORMAT_BGR10A2_SNORM_PACK32:
        case gli::format::FORMAT_BGR10A2_USCALED_PACK32:
        case gli::format::FORMAT_BGR10A2_SSCALED_PACK32:
        case gli::format::FORMAT_BGR10A2_UINT_PACK32:
        case gli::format::FORMAT_BGR10A2_SINT_PACK32:
        case gli::format::FORMAT_RGBA16_UNORM_PACK16:
        case gli::format::FORMAT_RGBA16_SNORM_PACK16:
        case gli::format::FORMAT_RGBA16_USCALED_PACK16:
        case gli::format::FORMAT_RGBA16_SSCALED_PACK16:
        case gli::format::FORMAT_RGBA16_UINT_PACK16:
        case gli::format::FORMAT_RGBA16_SINT_PACK16:
        case gli::format::FORMAT_RGBA16_SFLOAT_PACK16:
        case gli::format::FORMAT_RGBA32_UINT_PACK32:
        case gli::format::FORMAT_RGBA32_SINT_PACK32:
        case gli::format::FORMAT_RGBA32_SFLOAT_PACK32:
        case gli::format::FORMAT_RGBA64_UINT_PACK64:
        case gli::format::FORMAT_RGBA64_SINT_PACK64:
        case gli::format::FORMAT_RGBA64_SFLOAT_PACK64:
        case gli::format::FORMAT_RGBA_DXT1_UNORM_BLOCK8:
        case gli::format::FORMAT_RGBA_DXT1_SRGB_BLOCK8:
        case gli::format::FORMAT_RGBA_DXT3_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_DXT3_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_DXT5_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_DXT5_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_BP_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_BP_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ETC2_UNORM_BLOCK8:
        case gli::format::FORMAT_RGBA_ETC2_SRGB_BLOCK8:
        case gli::format::FORMAT_RGBA_ETC2_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ETC2_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_4X4_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_4X4_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_5X4_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_5X4_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_5X5_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_5X5_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_6X5_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_6X5_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_6X6_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_6X6_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_8X5_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_8X5_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_8X6_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_8X6_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_8X8_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_8X8_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X5_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X5_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X6_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X6_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X8_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X8_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X10_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_10X10_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_12X10_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_12X10_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_12X12_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ASTC_12X12_SRGB_BLOCK16:
        case gli::format::FORMAT_RGBA_PVRTC1_8X8_UNORM_BLOCK32:
        case gli::format::FORMAT_RGBA_PVRTC1_8X8_SRGB_BLOCK32:
        case gli::format::FORMAT_RGBA_PVRTC1_16X8_UNORM_BLOCK32:
        case gli::format::FORMAT_RGBA_PVRTC1_16X8_SRGB_BLOCK32:
        case gli::format::FORMAT_RGBA_PVRTC2_4X4_UNORM_BLOCK8:
        case gli::format::FORMAT_RGBA_PVRTC2_4X4_SRGB_BLOCK8:
        case gli::format::FORMAT_RGBA_PVRTC2_8X4_UNORM_BLOCK8:
        case gli::format::FORMAT_RGBA_PVRTC2_8X4_SRGB_BLOCK8:
        case gli::format::FORMAT_RGBA_ATCA_UNORM_BLOCK16:
        case gli::format::FORMAT_RGBA_ATCI_UNORM_BLOCK16:
        case gli::format::FORMAT_A8_UNORM_PACK8:
        case gli::format::FORMAT_LA8_UNORM_PACK8:
        case gli::format::FORMAT_A16_UNORM_PACK16:
        case gli::format::FORMAT_LA16_UNORM_PACK16:
            return true;
        default:
            return false;
    }
}

