#pragma once

#include "world/WorldData.h"

constexpr ui32 HEIGHTMAP_QUAD_SIZE = 2;

constexpr ui32 TERRAIN_MESH_WIDTH_QUADS = CHUNK_WIDTH / HEIGHTMAP_QUAD_SIZE;
constexpr ui32 TERRAIN_MESH_WIDTH_VERTS = TERRAIN_MESH_WIDTH_QUADS + 1;
constexpr ui32 TERRAIN_MESH_WIDTH_VERTS_SQ = SQ(TERRAIN_MESH_WIDTH_VERTS);
constexpr ui32 TERRAIN_MESH_SKIRT_VERTEX_COUNT = TERRAIN_MESH_WIDTH_VERTS * 4;
constexpr ui32 TERRAIN_MESH_SIZE_VERTS = SQ(TERRAIN_MESH_WIDTH_VERTS) + TERRAIN_MESH_SKIRT_VERTEX_COUNT;
constexpr ui32 TERRAIN_MESH_PADDED_WIDTH_VERTS = TERRAIN_MESH_WIDTH_VERTS + 2;
constexpr ui32 TERRAIN_MESH_PADDED_SIZE_VERTS = SQ(TERRAIN_MESH_PADDED_WIDTH_VERTS);

// Heightmap data
constexpr ui32 HEIGHTMAP_PATCH_WIDTH_CHUNKS = 2;
constexpr ui32 HEIGHTMAP_WIDTH = CHUNK_WIDTH * HEIGHTMAP_PATCH_WIDTH_CHUNKS;
constexpr ui32 HEIGHTMAP_QUAD_WIDTH_PER_PATCH = HEIGHTMAP_WIDTH / HEIGHTMAP_QUAD_SIZE;
constexpr ui32 HEIGHTMAP_VERT_WIDTH_PER_PATCH = HEIGHTMAP_QUAD_WIDTH_PER_PATCH + 1;
constexpr ui32 HEIGHTMAP_VERT_SIZE_PER_PATCH = SQ(HEIGHTMAP_VERT_WIDTH_PER_PATCH);
constexpr ui32 WORLD_WIDTH_HEIGHTMAP_PATCHES = WorldData::WORLD_WIDTH_CHUNKS / HEIGHTMAP_PATCH_WIDTH_CHUNKS;
constexpr ui32 WORLD_SIZE_HEIGHTMAP_PATCHES = SQ(WORLD_WIDTH_HEIGHTMAP_PATCHES);