#pragma once

#include "world/WorldDefaults.h"


// Quadtree data
constexpr int GRASS_QUADTREE_MAX_LOD = 5;
constexpr i32 TERRAIN_QUADTREE_MAX_LOD = 5;
constexpr i32 CHUNKS_PER_TERRAIN_QUADTREE = 32; // Must be power of two
constexpr i32 TERRAIN_QUADTREE_WIDTH = CHUNKS_PER_TERRAIN_QUADTREE * CHUNK_WIDTH;
constexpr i32 MIN_LOD_QUADTREE_WIDTH = (CHUNKS_PER_TERRAIN_QUADTREE >> (TERRAIN_QUADTREE_MAX_LOD - 1)) * CHUNK_WIDTH;

constexpr i32 HEIGHTMAP_QUAD_SIZE = 2;

// Terrain mesh data
constexpr i32 TERRAIN_MESH_WIDTH_QUADS = MIN_LOD_QUADTREE_WIDTH / HEIGHTMAP_QUAD_SIZE;
constexpr i32 TERRAIN_MESH_WIDTH_VERTS = TERRAIN_MESH_WIDTH_QUADS + 1;
constexpr i32 TERRAIN_MESH_WIDTH_VERTS_SQ = SQ(TERRAIN_MESH_WIDTH_VERTS);
constexpr i32 TERRAIN_MESH_SKIRT_VERTEX_COUNT = TERRAIN_MESH_WIDTH_VERTS * 4;
constexpr i32 WATER_MESH_SIZE_VERTS = SQ(TERRAIN_MESH_WIDTH_VERTS);
constexpr i32 TERRAIN_MESH_SIZE_VERTS = SQ(TERRAIN_MESH_WIDTH_VERTS) + TERRAIN_MESH_SKIRT_VERTEX_COUNT;
constexpr i32 TERRAIN_MESH_PADDED_WIDTH_VERTS = TERRAIN_MESH_WIDTH_VERTS + 2;
constexpr i32 TERRAIN_MESH_PADDED_SIZE_VERTS = SQ(TERRAIN_MESH_PADDED_WIDTH_VERTS);

// Heightmap data
constexpr i32 HEIGHTMAP_PATCH_WIDTH_CHUNKS = 2;
constexpr i32 HEIGHTMAP_WIDTH = CHUNK_WIDTH * HEIGHTMAP_PATCH_WIDTH_CHUNKS;
constexpr i32 HEIGHTMAP_QUAD_WIDTH_PER_PATCH = HEIGHTMAP_WIDTH / HEIGHTMAP_QUAD_SIZE;
constexpr i32 HEIGHTMAP_VERT_WIDTH_PER_PATCH = HEIGHTMAP_QUAD_WIDTH_PER_PATCH + 1;
constexpr i32 HEIGHTMAP_VERT_SIZE_PER_PATCH = SQ(HEIGHTMAP_VERT_WIDTH_PER_PATCH);