#pragma once

constexpr ui32 HEIGHTMAP_QUAD_SIZE = 4;

constexpr ui32 TERRAIN_MESH_WIDTH_QUADS = CHUNK_WIDTH / HEIGHTMAP_QUAD_SIZE;
constexpr ui32 TERRAIN_MESH_WIDTH_VERTS = TERRAIN_MESH_WIDTH_QUADS + 1;
constexpr ui32 TERRAIN_MESH_WIDTH_VERTS_SQ = SQ(TERRAIN_MESH_WIDTH_VERTS);
constexpr ui32 TERRAIN_MESH_SKIRT_VERTEX_COUNT = TERRAIN_MESH_WIDTH_VERTS * 4;
constexpr ui32 TERRAIN_MESH_SIZE_VERTS = SQ(TERRAIN_MESH_WIDTH_VERTS) + TERRAIN_MESH_SKIRT_VERTEX_COUNT;
constexpr ui32 TERRAIN_MESH_PADDED_WIDTH_VERTS = TERRAIN_MESH_WIDTH_VERTS + 2;
constexpr ui32 TERRAIN_MESH_PADDED_SIZE_VERTS = SQ(TERRAIN_MESH_PADDED_WIDTH_VERTS);