#pragma once

// ====================== HEIGHTMAP ======================
constexpr i32 HEIGHTMAP_QUAD_SIZE = 2;
constexpr i32 HEIGHTMAP_PATCH_WIDTH_CHUNKS = 2;
constexpr i32 HEIGHTMAP_PATCH_WIDTH_TILES = CHUNK_WIDTH * HEIGHTMAP_PATCH_WIDTH_CHUNKS;
constexpr i32 HEIGHTMAP_QUAD_WIDTH_PER_PATCH = HEIGHTMAP_PATCH_WIDTH_TILES / HEIGHTMAP_QUAD_SIZE;
constexpr i32 HEIGHTMAP_VERT_WIDTH_PER_PATCH = HEIGHTMAP_QUAD_WIDTH_PER_PATCH;
constexpr i32 HEIGHTMAP_VERT_SIZE_PER_PATCH = SQ(HEIGHTMAP_VERT_WIDTH_PER_PATCH);

// ====================== BIOMES ======================
constexpr i32 BIOME_VERTEX_STRIDE = BLOCK_WIDTH;
constexpr ui32 BIOME_PATCH_WIDTH_TILES = CHUNK_WIDTH * 2;
constexpr ui32 BIOME_PATCH_WIDTH_VERTS = BIOME_PATCH_WIDTH_TILES / BIOME_VERTEX_STRIDE;
constexpr ui32 BIOME_PATCH_SIZE_VERTS = SQ(BIOME_PATCH_WIDTH_VERTS);